#!/usr/bin/env bash

export NVIM_APPNAME="nvim-LunarVim"
export LUNARVIM_RUNTIME_DIR="${HOME}/.local/share/${NVIM_APPNAME}"
export LUNARVIM_CONFIG_DIR="${HOME}/.config/${NVIM_APPNAME}"
export LUNARVIM_CACHE_DIR="${HOME}/.cache/${NVIM_APPNAME}"
export LUNARVIM_BASE_DIR="${HOME}/.config/${NVIM_APPNAME}"

exec -a "$NVIM_APPNAME" nvim "$@"
